export const industries  = [
    "RestaurantsAndCafes",
    "SoftwareEngineering",
    "Accounting",
    "Healthcare",
    "Education",
    "Retail",
    "Manufacturing",
    "Finance",
    "Construction",
    "Transportation",
    "Marketing",
    "RealEstate",
    "LegalServices",
    "Entertainment",
    "Hospitality",
    "Telecommunications",
    "Other"
];
