// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Entities.Enums;
using Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#pragma warning disable 219, 612, 618
#nullable disable

namespace JobSync.Repository.CompiledModels
{
    internal partial class JobBenefitEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Entities.Models.JobBenefit",
                typeof(JobBenefit),
                baseEntityType);

            var jobId = runtimeEntityType.AddProperty(
                "JobId",
                typeof(Guid),
                propertyInfo: typeof(JobBenefit).GetProperty("JobId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(JobBenefit).GetField("<JobId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            jobId.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    (Guid v1, Guid v2) => v1 == v2,
                    (Guid v) => v.GetHashCode(),
                    (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    (Guid v1, Guid v2) => v1 == v2,
                    (Guid v) => v.GetHashCode(),
                    (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    (Guid v1, Guid v2) => v1 == v2,
                    (Guid v) => v.GetHashCode(),
                    (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uniqueidentifier"));
            jobId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var benefit = runtimeEntityType.AddProperty(
                "Benefit",
                typeof(Benefit),
                propertyInfo: typeof(JobBenefit).GetProperty("Benefit", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(JobBenefit).GetField("<Benefit>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            benefit.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<Benefit>(
                    (Benefit v1, Benefit v2) => object.Equals((object)v1, (object)v2),
                    (Benefit v) => v.GetHashCode(),
                    (Benefit v) => v),
                keyComparer: new ValueComparer<Benefit>(
                    (Benefit v1, Benefit v2) => object.Equals((object)v1, (object)v2),
                    (Benefit v) => v.GetHashCode(),
                    (Benefit v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                converter: new ValueConverter<Benefit, int>(
                    (Benefit value) => (int)value,
                    (int value) => (Benefit)value),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<Benefit, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<Benefit, int>(
                        (Benefit value) => (int)value,
                        (int value) => (Benefit)value)));
            benefit.SetSentinelFromProviderValue(0);
            benefit.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { jobId, benefit });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("JobId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.ClientCascade,
                required: true);

            var job = declaringEntityType.AddNavigation("Job",
                runtimeForeignKey,
                onDependent: true,
                typeof(Job),
                propertyInfo: typeof(JobBenefit).GetProperty("Job", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(JobBenefit).GetField("<Job>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var benefits = principalEntityType.AddNavigation("Benefits",
                runtimeForeignKey,
                onDependent: false,
                typeof(List<JobBenefit>),
                propertyInfo: typeof(Job).GetProperty("Benefits", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Job).GetField("<Benefits>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Benefits");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
